#!/usr/bin/env bash

# Stop the running FTS server
echo "Stopping the running FTS server..."
apachectl -k stop                  # FTS REST frontend & FTSMON
ps ax awk '/fts3_/{ print $1 }' | xargs kill -9

# Prepare local FTS3 repo
echo "Rebuilding FTS3..."
cd /fts3/packaging
yum-builddep -y rpm/fts.spec
make rpm
createrepo out
createrepo out/x86_64

# Remove the old fts server and install the local one
echo "Installing FTS3 from the local repo..."
dnf remove -y fts-libs fts-server
dnf install -y fts-server fts-mysql fts-msg

echo "Following files are [re]installed:"
dnf repoquery -y fts-server fts-mysql fts-msg

